name: shambadunia
description: Shambadunia ecommerce App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+14

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  carousel_slider: ^1.3.1
  shared_preferences: ^0.5.6
  intl: ^0.16.0
  http: ^0.12.0+2
  flutter_html: ^0.11.1
  share: ^0.6.3+1
  geolocator: ^5.1.5
  flutter_google_places: ^0.2.3
  date_format: ^1.0.6
  image_picker: ^0.6.2+3
  google_maps_flutter: ^0.5.21+12
  flutter_staggered_grid_view: ^0.3.0
  intro_slider: ^2.2.8
  flutter_custom_dialog: ^1.0.16
  firebase_core: ^0.4.0
  firebase_auth: ^0.11.1+6
  google_sign_in: ^4.1.1
  cloud_firestore: ^0.12.5
  firebase_messaging: ^5.0.2
  location_permissions: ^2.0.4+1
  cached_network_image: ^2.0.0
  sms_otp_auto_verify: ^1.2.2
  modal_bottom_sheet: ^0.2.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_native_splash:
  image: assets/images/about.png
  color: "ffffff"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/logo.png
    - assets/images/tractor.png
    - assets/images/truck.png
    - assets/images/nyanya.jpg
    - assets/images/mahindi.jpg
    - assets/images/machine.jpeg
    - assets/images/loading.gif
    - assets/images/airtelmoney.png
    - assets/images/mpesa.png
    - assets/images/tigopesa.png
    - assets/images/buy.png
    - assets/images/sell.png
    - assets/images/register.png
    - assets/images/track.png
    - assets/images/invest.png
    - assets/images/placeholder.jpg
    - assets/images/bajaji.jpg
    - assets/images/bodaboda.jpg
    - assets/images/kirikuu.jpg
    - assets/images/welcome.jpg
    - assets/images/payments.jpg
    - assets/images/welcome.png
    - assets/images/payments.png
    - assets/images/delivery.jpg
    - assets/images/icon-user.png
    - assets/images/gmail.png
    - assets/images/pin.png
    - assets/images/order.png
    - assets/images/news.png
    - assets/images/about.png
    - assets/images/logo2.png
    - assets/images/productss.jpg
    - assets/categories.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
